In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow import keras
import pickle

WARNING:tensorflow:From e:\ANN Churn Project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [3]:
## Load the dataset
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
## Preprocess the data
# Drop unnecessary columns
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [6]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
## Encoding categorical variables
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [ ]:
## One-hot encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder() 
Geography_encoded = OHE.fit_transform(df[['Geography']])
Geography_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [10]:
OHE.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
Geography_encode_df = pd.DataFrame(Geography_encoded.toarray(), columns=OHE.get_feature_names_out())
Geography_encode_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [13]:
## Concatenate the one-hot encoded columns back to the original dataframe
df = pd.concat([df, Geography_encode_df], axis=1)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,France,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,France,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [14]:
df.drop('Geography', axis=1, inplace=True)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [15]:
## Save the encoders for future use
with open('label_encoder.pkl', 'wb') as le_file:
    pickle.dump(label_encoder, le_file)

with open('onehot_encoder.pkl', 'wb') as ohe_file:
    pickle.dump(OHE, ohe_file)

In [ ]:
## Split the data into features and target variable
X = df.drop('Exited', axis=1)
y = df['Exited']
## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
## Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
## Save the scaler for future use
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

## Artificial Neural Network Implementation

In [19]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [20]:
## Build the ANN model
model = Sequential([
Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
Dense(32, activation='relu'),
Dense(1, activation='sigmoid')





]



)

WARNING:tensorflow:From e:\ANN Churn Project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [27]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.BinaryCrossentropy()

In [28]:
## compile the model
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

In [ ]:
## Set up early stopping and TensorBoard callbacks
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [30]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [31]:
## Train the model
history = model.fit(X_train_scaled, y_train, validation_split=0.2, epochs=100, batch_size=32, callbacks=[early_stopping_callback, tensorboard_callback])

Epoch 1/100
WARNING:tensorflow:From e:\ANN Churn Project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\ANN Churn Project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

200/200 [==============================] - 2s 4ms/step - loss: 0.4671 - accuracy: 0.8011 - val_loss: 0.4132 - val_accuracy: 0.8288
Epoch 2/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8302 - val_loss: 0.3867 - val_accuracy: 0.8425
Epoch 3/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3723 - accuracy: 0.8467 - val_loss: 0.3651 - val_accuracy: 0.8481
Epoch 4/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8559 - val_loss: 0.3563 - val_accuracy: 0.8512
Epoch 5/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3430 - accuracy: 0.8598 - val_loss: 0.3533 - val_accuracy: 0.8537
Epoch 6/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3381 - accuracy: 0.8609 - val_loss: 0.3479 - val_accuracy: 0.8500
Epoch 7/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8625 - val_loss: 0.3481 - val_accuracy: 0.8519
Epoch 8/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3317 - accuracy: 0.8639 - val_loss: 0.3482 - val_accuracy: 0.8594
Epoch 9/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3281 - accuracy: 0.8653 - val_loss: 0.3469 - val_accuracy: 0.8531
Epoch 10/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3260 - accuracy: 0.8669 - val_loss: 0.3433 - val_accuracy: 0.8544
Epoch 11/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3234 - accuracy: 0.8691 - val_loss: 0.3454 - val_accuracy: 0.8550
Epoch 12/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3207 - accuracy: 0.8675 - val_loss: 0.3429 - val_accuracy: 0.8512
Epoch 13/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3193 - accuracy: 0.8681 - val_loss: 0.3473 - val_accuracy: 0.8506
Epoch 14/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3174 - accuracy: 0.8702 - val_loss: 0.3459 - val_accuracy: 0.8506
Epoch 15/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3147 - accuracy: 0.8712 - val_loss: 0.3432 - val_accuracy: 0.8575
Epoch 16/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3136 - accuracy: 0.8714 - val_loss: 0.3506 - val_accuracy: 0.8581
Epoch 17/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3119 - accuracy: 0.8709 - val_loss: 0.3449 - val_accuracy: 0.8500
Epoch 18/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3094 - accuracy: 0.8733 - val_loss: 0.3435 - val_accuracy: 0.8519
Epoch 19/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.8731 - val_loss: 0.3455 - val_accuracy: 0.8525
Epoch 20/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3069 - accuracy: 0.8748 - val_loss: 0.3447 - val_accuracy: 0.8575
Epoch 21/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3044 - accuracy: 0.8733 - val_loss: 0.3473 - val_accuracy: 0.8537
Epoch 22/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3035 - accuracy: 0.8770 - val_loss: 0.3494 - val_accuracy: 0.8519

In [32]:
## Save model
model.save('churn_model.h5')

e:\ANN Churn Project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [ ]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [35]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 30464), started 0:01:04 ago. (Use '!kill 30464' to kill it.)